/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package labs.client;

import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import labs.MBuilder;
import labs.IObserver;
import labs.Model;
import labs.Pnt;

public class ClientPanel extends javax.swing.JPanel implements IObserver {

    Model m = MBuilder.build();
    ClientFrame frame;
    
    /**
     * Creates new form VModel
     */
    public ClientPanel() {
        initComponents();
        m.addObserver(this);
    }

    @Override
    public void refresh() {
        this.repaint();
    }

    public void setFrame(ClientFrame frame) {
        this.frame = frame;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(204, 204, 204));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 398, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 298, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        Pnt clickPnt = new Pnt(evt.getX(), evt.getY());
        if (frame != null)
            frame.sendPnt(clickPnt);
    }//GEN-LAST:event_formMouseClicked

    @Override
    protected void paintComponent(Graphics g) { 
        super.paintComponent(g);
        
        g.setColor(Color.BLACK);
        
        Graphics2D g2d = (Graphics2D)g;
        g2d.setStroke(new BasicStroke(3));

        g2d.setColor(Color.red);
        
        Pnt pnt = m.getPnt();
        if (pnt != null) {
            int pntX = pnt.getX();
            int pntY = pnt.getY();

            g2d.drawLine(pntX,0, pntX,getHeight());
            g2d.drawLine(0,pntY, getWidth(),pntY);
        }
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
